name: Build jar and publish it in a docker container
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Build artifact
        run: mkdir -p target/build && ./sbt assembly

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./target/build/BungeeSemaphore.jar
          draft: false
          prerelease: false
          tag_name: release-at-${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
